### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by bcrosser** [Antrikshy/Tinseltown.js#1]
Everything just flickers in place, but nothing appears to have any effects associated with it.

Repro:
Go to http://antrikshy.com/Tinseltown.js/ in Firefox with no add-ons.

Expected:
Flickering that looks fancy.

Actual:
Flickering that looks like the page is broken.

**Comment by Antrikshy** [comment]
For posterity, I found the problem, fixed it in commit https://github.com/Antrikshy/Tinseltown.js/commit/34691ef703008e340aa04c06246f851f181f57f9, and forgot about this issue. 😄
